version: 2
 
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - python -m pip install sphinx-autobuild sphinx_rtd_theme
      - python -m pip install nbsphinx
      - python -m pip install recommonmark
 
python:
  install:
    - method: pip
      path: .


sphinx:
  fail_on_warning: false
  configuration: docs/source/conf.py