version: 2
 
build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - python -m pip install sphinx-autobuild sphinx_rtd_theme
      - python -m pip install nbsphinx
      - python -m pip install recommonmark
 
python:
  install:
    - method: pip
      path: .

# Build documentation in the docs/ directory with Sphinx

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true